"""empty message

Revision ID: 683a87de5b31
Revises: 
Create Date: 2023-02-01 18:59:33.225412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683a87de5b31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dermatological_profile',
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('eyes_color', sa.Enum('LIGHT_BLUE_GREEN_GREY', 'BLUE_GREEN_GREY', 'DARK_BLUE_GREEN_LIGHT_BROWN', 'DARK_BROWN', 'BROWISH_BLACK', name='eyescolor'), nullable=True),
    sa.Column('hair_color', sa.Enum('RED', 'BLONDIE', 'CHESNUT_DARK_BLONDIE', 'DARK_BROWN', 'BLACK', name='haircolor'), nullable=True),
    sa.Column('skin_color', sa.Enum('PINK', 'VERY_PALE', 'LIGHT_BROWN_OLIVE', 'BROWN', 'DARK_BROWN', name='skincolor'), nullable=True),
    sa.Column('freckles', sa.Enum('MANY', 'SEVERAL', 'FEW', 'RARE', 'NONE', name='freckles'), nullable=True),
    sa.Column('skin_stay_in_the_sun', sa.Enum('SEVERE_BURNS', 'MODERATE_BURNS', 'SOMETIME_BURNS', 'RARE_BURNS', 'NO_BURNS', name='skinstayinthesun'), nullable=True),
    sa.Column('turn_brown', sa.Enum('NEVER', 'RARELY', 'SOMETHIMES', 'OFTEN', 'ALWAYS', name='turnbrown'), nullable=True),
    sa.Column('how_brown', sa.Enum('HARDLY', 'LIGHT_TAN', 'MEDIUM_TAN', 'DARK_TAN', 'VERY_DARK_TAN', name='howbrown'), nullable=True),
    sa.Column('how_often_tan', sa.Enum('NEVER', 'RARELY', 'SOMETIMES', 'OFTEN', 'ALWAYS', name='howoftentan'), nullable=True),
    sa.Column('artificial_time_expose', sa.Enum('MORE_THREE_MONTHS', 'LAST_TWO_THREE_MONTHS', 'LAST_ONE_TWO_MONTS', 'LAST_WEEK', 'LAST_DAY', name='artificialtimeexpose'), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('doctor',
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('names', sa.String(length=50), nullable=True),
    sa.Column('surnames', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('medical_license', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient',
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('names', sa.String(length=50), nullable=True),
    sa.Column('surnames', sa.String(length=40), nullable=True),
    sa.Column('bithdate', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('dermatological_profile_uuid', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dermatological_profile_uuid'], ['dermatological_profile.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('doctor')
    op.drop_table('dermatological_profile')
    # ### end Alembic commands ###
