"""empty message

Revision ID: b7bba76c6035
Revises: 683a87de5b31
Create Date: 2023-02-05 14:11:55.570637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7bba76c6035'
down_revision = '683a87de5b31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dermatological_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_sensitive', sa.Enum('VERY_SENSITIVE', 'SENSITIVE', 'MILDLY_SENSITIVE', 'RESISTANT', 'VERY_RESISTANT', name='facesensitive'), nullable=True))

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=50), nullable=True))
        batch_op.drop_column('bithdate')
        batch_op.drop_column('surnames')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surnames', sa.VARCHAR(length=40), nullable=True))
        batch_op.add_column(sa.Column('bithdate', sa.DATETIME(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('dermatological_profile', schema=None) as batch_op:
        batch_op.drop_column('face_sensitive')

    # ### end Alembic commands ###
