"""empty message

Revision ID: bec8c42a79a9
Revises: e599192708be
Create Date: 2023-02-05 19:58:44.813244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec8c42a79a9'
down_revision = 'e599192708be'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('age')

    # ### end Alembic commands ###
