"""empty message

Revision ID: e599192708be
Revises: b7bba76c6035
Create Date: 2023-02-05 18:27:02.439558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e599192708be'
down_revision = 'b7bba76c6035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('speciality', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_column('speciality')
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
